---
kind: pipeline
type: docker
name: default

steps:
  - name: validate terraform
    image: hashicorp/terraform:1.3.7
    commands:
      - "cd production"
      - "terraform --version"
      - "terraform init -backend=false -input=false"
      - "terraform validate"

  - name: lint terraform
    image: ghcr.io/terraform-linters/tflint:latest
    commands:
      - "tflint --init"
      - "tflint --version"
      - "find production -name *.tf | xargs tflint"

  - name: notify on failure
    image: drillster/drone-email
    settings:
      host: smtp.internal.loganmarchione.xyz
      port: 25
      from: donotreply@loganmarchione.com
      from.name: "[Alert from Drone CI/CD]"
    when:
      status:
        - failure