---
name: Terraform Scan

on:
  push:
    paths:
      - 'terraform/**'
  pull_request:
  schedule:
    - cron: "0 5 * * 0"
  workflow_dispatch:

defaults:
  run:
    working-directory: terraform/production

jobs:
  terrascan:
    name: Terrascan

    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Run Terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_dir: ./terraform/production
          config_path: ./terraform/production/.terrascan.toml
          verbose: true

  kics:
    name: KICS

    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3 

      - name: Run KICS
        uses: Checkmarx/kics-github-action@v1.7.0
        with:
           path: ./terraform/production
           config_path: ./terraform/production/.kics.yml

  tfsec:
    name: tfsec

    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3 

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ./terraform/production
          additional_args: --config-file ./terraform/production/.tfsec.yml
