---
name: Terraform Lint

on:
  push:
    paths:
      - 'terraform/**'
  schedule:
    - cron: "0 5 * * 0"
  workflow_dispatch:

defaults:
  run:
    working-directory: terraform/production


jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
