---
name: Terraform Scan

on:
  push:
    paths:
      - 'terraform/**'
  pull_request:
  schedule:
    - cron: "0 5 * * 0"
  workflow_dispatch:

defaults:
  run:
    working-directory: terraform/production

jobs:
  terrascan:
    name: Terrascan

    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Run Terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_dir: ./terraform/production
          config_path: ./terraform/production/.terrascan.toml
          non_recursive: true
          skip_rules: AWS.S3Bucket.EncryptionandKeyManagement.High.0405

  kics:
    name: KICS

    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3 

      - name: Run KICS
        uses: Checkmarx/kics-github-action@v1.6.3
        with:
           path: ./terraform/production
           fail_on: high

  tfsec:
    name: tfsec

    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3 

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          additional_args: --exclude aws-s3-encryption-customer-key
