---
name: Terraform Lint

on:
  push:
    paths:
      - 'terraform/**'
  schedule:
    - cron: "0 5 * * 0"
  workflow_dispatch:

defaults:
  run:
    working-directory: terraform/production

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Terraform version
        run: terraform version

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init -backend=false -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: TFLint version
        run: tflint --version

      - name: TFLint init
        run: tflint --init

      - name: TFLint validate
        run: tflint
