---
name: Terraform Scan

on:
  push:
    paths:
      - 'terraform/**'
  pull_request:
  schedule:
    - cron: "0 5 * * 0"
  workflow_dispatch:

defaults:
  run:
    working-directory: terraform/production

jobs:
  terraform_scan:
    name: Terraform Scan

    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Run Terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_dir: ./terraform

      - name: KICS Github Action
        uses: Checkmarx/kics-github-action@v1.6
        with:
           path: '.'
